# Javascript CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.0

orbs:
  heroku: circleci/heroku@1.2.4

jobs:
  checkout_code:
    docker:
      - image: circleci/node:12.18.3-stretch-browsers
    working_directory: ~/just-walking
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/just-walking

  install_packages:
    docker:
      - image: circleci/node:12.18.3-stretch-browsers
    working_directory: ~/just-walking
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - yarn-packages-v3-{{ checksum "yarn.lock" }}
      - run:
          name: Install yarn pacakges
          command: yarn
      - save_cache: # special step to save the dependency cache
          name: Save Yarn Package Cache
          key: yarn-packages-v3-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  tests:
    docker:
      - image: circleci/node:12.18.3-stretch-browsers
    working_directory: ~/just-walking
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - yarn-packages-v3-{{ checksum "yarn.lock" }}
      - run:
          name: test
          command: yarn test --maxWorkers=2
      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml


workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - install_packages:
          requires:
            - checkout_code
      - tests:
          requires:
            - install_packages
      - heroku/deploy-via-git:
           requires:
             - tests # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master
